sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: VFc8bk9demlMaLopndiFvjT3zM0O/IQdubGJZXFz9tqq5N1e4yeMpm3LWg7RymkOBmJV60OrniqZPDT9NpS3LYeLsCcdbk0f5E6wd/ra5Tp9Lqqn6UNlTQMua9bzyPzIHfkSDOx2V9VUeG5k4jsg4bGhcC9onpDWHLPuFyPutPW0LSOser3gV0JgqPfAlZmZtrRFF9Y+D6ja0oyvGDtFopn94piO1Qg/7PnWQeo2JYkjZ7QwN7gKmZ/3plLlXk0CEAdI7dNLrtigMzLo0XUuJAecDNEF5e23MeR5IkQx9g8iYHnTwMKTlDSS1+FrsQfWbm3/fjF5Cai+21REB/GFeMMdWiSKxtLFFkm2SE6PfQeV21haI/iHSg7wWs3Jrf5pgXuNVwve6Pmrv12MJDfC8aA8pLuLxdEDpsu4SxZooGZV6xaDy8+FbeQ1N67jrGNlnfB2OO4EXrfZE2m8ZyrT3YjNUwe+Il3cmRlEi6MNBmaDANN8EGO1+uhdwZq6rd1HL5xEyiskJ3Ontd1eQx/pZVfBV4AjJCWLinSnYM6sdnBBrKeYnXTAPjuLsW/5b29G93NR24mC0OY126toaqhn2QEkWINoqZZB4pV34gCFznj0ohvXI7FWfIHRYnLAxUXQsgxZSfUoYKEma7bXWDffASRto9uZ0CMYzOw+DAepGy8=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/The-Voice-of-the-City--Further-Stories-of-the-Four-Million_1444
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy